<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\Economy\CurrencyEnum;
use App\Enums\Equipment\ProfileEnum;
use App\Enums\Equipment\RepairEnum;
use App\Enums\Equipment\SlotEnum;
use App\Enums\Equipment\TypeEnum;
use App\Models\Equipment;
use Illuminate\Database\Seeder;

final class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->catalog() as $row) {
            $equipment = Equipment::query()->updateOrCreate(
                ['item_id' => $row['item_id']],
                $row,
            );

            $this->syncAppearanceImage($equipment);
        }
    }

    /**
     * Initial catalog snapshot for fresh installs / tests. Runtime SoT = `equipment` table.
     *
     * @return list<array<string, mixed>>
     */
    private function catalog(): array
    {
        $rows = [
            [
                'item_id' => 'knuckles_0',
                'name' => 'Кастет уличного бойца',
                'description' => 'Класс «кастет»: уворот и крит. Базовый экземпляр на 0 уровне.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::KNUCKLES,
                'in_shop' => false,
                'enabled' => true,
                'price' => 0,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 1,
                'weapon_damage_max' => 2,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 2,
                'mf_anti_dodge' => 0,
                'mf_crit' => 2,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 0,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_0',
                'name' => 'Учебный нож',
                'description' => 'Лёгкий учебный клинок. Чуть повышает уворот и шанс крита.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::KNIFE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 2,
                'weapon_damage_max' => 3,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 6,
                'mf_anti_dodge' => 0,
                'mf_crit' => 2,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 1,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_0',
                'name' => 'Учебный топор',
                'description' => 'Тяжёлый учебный топор. Бьёт сильнее и чаще критикует.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::AXE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 3,
                'weapon_damage_max' => 4,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 2,
                'mf_crit' => 6,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 2,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_0',
                'name' => 'Учебная дубина',
                'description' => 'Простая дубина тренера. Держит антиуворот и антикрит.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::CLUB,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 3,
                'weapon_damage_max' => 4,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 4,
                'mf_crit' => 0,
                'mf_anti_crit' => 4,
                'effect_value' => null,
                'sort_order' => 3,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_1',
                'name' => 'Короткий кинжал',
                'description' => 'Короткий кинжал новичка. Ставка на уворот и точные удары.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::KNIFE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 4,
                'weapon_damage_max' => 5,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 10,
                'mf_anti_dodge' => 2,
                'mf_crit' => 4,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 4,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_1',
                'name' => 'Лёгкий топор',
                'description' => 'Лёгкий боевой топор. Хороший крит за умеренную цену.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::AXE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 5,
                'weapon_damage_max' => 6,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 4,
                'mf_crit' => 10,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 5,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_1',
                'name' => 'Дубина новобранца',
                'description' => 'Дубина для строя. Усиливает контроль уворота и крита врага.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::CLUB,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 5,
                'weapon_damage_max' => 6,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 6,
                'mf_crit' => 2,
                'mf_anti_crit' => 6,
                'effect_value' => null,
                'sort_order' => 6,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_2',
                'name' => 'Боевой нож',
                'description' => 'Боевой нож наёмника. Заметно быстрее и острее учебного.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::KNIFE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 100,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 7,
                'weapon_damage_max' => 9,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 16,
                'mf_anti_dodge' => 4,
                'mf_crit' => 6,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 7,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_2',
                'name' => 'Боевой топор',
                'description' => 'Боевой топор рейдера. Высокий крит и давление в ближнем бою.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::AXE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 100,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 8,
                'weapon_damage_max' => 10,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 8,
                'mf_crit' => 16,
                'mf_anti_crit' => 2,
                'effect_value' => null,
                'sort_order' => 8,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_2',
                'name' => 'Окованная дубина',
                'description' => 'Окованная дубина стража. Крепкий антикрит и антиуворот.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::CLUB,
                'in_shop' => true,
                'enabled' => true,
                'price' => 100,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 8,
                'weapon_damage_max' => 10,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 2,
                'mf_anti_dodge' => 10,
                'mf_crit' => 4,
                'mf_anti_crit' => 12,
                'effect_value' => null,
                'sort_order' => 9,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_3',
                'name' => 'Кинжал ассасина',
                'description' => 'Кинжал ассасина. Максимальный уворот в линейке ножей.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::KNIFE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::VIP,
                'weapon_damage_min' => 11,
                'weapon_damage_max' => 13,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 24,
                'mf_anti_dodge' => 8,
                'mf_crit' => 10,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 10,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_3',
                'name' => 'Топор берсерка',
                'description' => 'Топор берсерка. Пиковый крит и тяжёлый удар.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::AXE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::VIP,
                'weapon_damage_min' => 12,
                'weapon_damage_max' => 14,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 14,
                'mf_crit' => 24,
                'mf_anti_crit' => 4,
                'effect_value' => null,
                'sort_order' => 11,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_3',
                'name' => 'Дубина стража',
                'description' => 'Тяжёлая дубина стража. Максимальный антикрит и антиуворот в линейке.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::CLUB,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::VIP,
                'weapon_damage_min' => 12,
                'weapon_damage_max' => 14,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 4,
                'mf_anti_dodge' => 14,
                'mf_crit' => 6,
                'mf_anti_crit' => 18,
                'effect_value' => null,
                'sort_order' => 12,
                'repairable' => true,
            ],
            [
                'item_id' => 'hammer_1',
                'name' => 'Молот стража',
                'description' => 'Молот стража. Крит и сильный антиуворот; VIP-ремонт.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::HAMMER,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::VIP,
                'weapon_damage_min' => 12,
                'weapon_damage_max' => 14,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 16,
                'mf_crit' => 16,
                'mf_anti_crit' => 6,
                'effect_value' => null,
                'sort_order' => 13,
                'repairable' => true,
            ],
            [
                'item_id' => 'heavy_0',
                'name' => 'Кольчуга',
                'description' => 'Кольчуга новобранца. Запас HP и базовая броня груди.',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::ARMOR,
                'profile' => ProfileEnum::HEAVY,
                'in_shop' => false,
                'enabled' => true,
                'price' => 0,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 15,
                'armor' => 2,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 13,
                'repairable' => true,
            ],
            [
                'item_id' => 'mobile_0',
                'name' => 'Кожаный шлем',
                'description' => 'Лёгкий шлем новичка. Чуть повышает запас HP и уворот.',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::HELMET,
                'profile' => ProfileEnum::MOBILE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 25,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 5,
                'armor' => 1,
                'mf_dodge' => 2,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 15,
                'repairable' => true,
            ],
            [
                'item_id' => 'mobile_1',
                'name' => 'Кожаные сапоги',
                'description' => 'Лёгкие сапоги новичка. Чуть повышают запас HP и антиуворот.',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::BOOTS,
                'profile' => ProfileEnum::MOBILE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 25,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 5,
                'armor' => 1,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 2,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 16,
                'repairable' => true,
            ],
            [
                'item_id' => 'mobile_2',
                'name' => 'Кожаные штаны',
                'description' => 'Простые штаны новичка. Броня пояса и чуть HP.',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::PANTS,
                'profile' => ProfileEnum::MOBILE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 25,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 4,
                'armor' => 1,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 1,
                'effect_value' => null,
                'sort_order' => 17,
                'repairable' => true,
            ],
            [
                'item_id' => 'mobile_3',
                'name' => 'Кожаные перчатки',
                'description' => 'Лёгкие перчатки новичка. Чуть антикрита и HP.',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::GLOVES,
                'profile' => ProfileEnum::MOBILE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 3,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 2,
                'effect_value' => null,
                'sort_order' => 21,
                'repairable' => true,
            ],
            [
                'item_id' => 'sword_0',
                'name' => 'Учебный меч',
                'description' => 'Учебный меч. Баланс уворота и антиуворота.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::SWORD,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 4,
                'weapon_damage_max' => 5,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 6,
                'mf_anti_dodge' => 6,
                'mf_crit' => 2,
                'mf_anti_crit' => 2,
                'effect_value' => null,
                'sort_order' => 18,
                'repairable' => true,
            ],
            [
                'item_id' => 'hammer_0',
                'name' => 'Учебный молот',
                'description' => 'Учебный молот. Крит и антиуворот.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::HAMMER,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 5,
                'weapon_damage_max' => 6,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 8,
                'mf_crit' => 8,
                'mf_anti_crit' => 2,
                'effect_value' => null,
                'sort_order' => 20,
                'repairable' => true,
            ],
            [
                'item_id' => 'heavy_1',
                'name' => 'Деревянный баклер',
                'description' => 'Лёгкий щит. Второй блок в раунде и антикрит.',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::SHIELD,
                'profile' => ProfileEnum::HEAVY,
                'in_shop' => true,
                'enabled' => true,
                'price' => 35,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 2,
                'mf_crit' => 0,
                'mf_anti_crit' => 8,
                'effect_value' => null,
                'sort_order' => 22,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_4',
                'name' => 'Короткий нож',
                'description' => 'Лёгкий нож: можно в любую руку. Вместе со вторым ножом/кастетом — два удара. Нельзя со щитом во второй руке.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => ProfileEnum::KNIFE,
                'in_shop' => true,
                'enabled' => true,
                'price' => 30,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 2,
                'weapon_damage_max' => 3,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 2,
                'mf_anti_dodge' => 0,
                'mf_crit' => 4,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 23,
                'repairable' => true,
            ],
            [
                'item_id' => 'focus_0',
                'name' => 'Медное кольцо',
                'description' => 'Простое кольцо. Чуть уворота.',
                'item_type' => TypeEnum::JEWELRY,
                'slot' => SlotEnum::RING_1,
                'profile' => ProfileEnum::FOCUS,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 3,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 24,
                'repairable' => true,
            ],
            [
                'item_id' => 'charm_0',
                'name' => 'Бронзовое кольцо',
                'description' => 'Кольцо на вторую руку. Чуть крита.',
                'item_type' => TypeEnum::JEWELRY,
                'slot' => SlotEnum::RING_2,
                'profile' => ProfileEnum::CHARM,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 3,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 25,
                'repairable' => true,
            ],
            [
                'item_id' => 'vital_0',
                'name' => 'Костяной амулет',
                'description' => 'Амулет новичка. Запас HP.',
                'item_type' => TypeEnum::JEWELRY,
                'slot' => SlotEnum::AMULET,
                'profile' => ProfileEnum::VITAL,
                'in_shop' => true,
                'enabled' => true,
                'price' => 30,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 10,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_value' => null,
                'sort_order' => 26,
                'repairable' => true,
            ],
            [
                'item_id' => 'heal_0',
                'name' => 'Зелье лечения',
                'description' => 'Флакон красного зелья. Восстанавливает HP в бою.',
                'item_type' => TypeEnum::POTION,
                'slot' => SlotEnum::POCKET,
                'profile' => ProfileEnum::HEAL,
                'in_shop' => true,
                'enabled' => true,
                'price' => 15,
                'currency' => CurrencyEnum::SILVER,
                'repair_tier' => RepairEnum::NORMAL,
                'weapon_damage_min' => 0,
                'weapon_damage_max' => 0,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_value' => 40,
                'sort_order' => 14,
                'repairable' => false,
            ],
        ];

        foreach ($rows as $idx => $row) {
            foreach ($this->reqsForItem($row['item_id']) as $key => $value) {
                $rows[$idx][$key] = $value;
            }
        }

        for ($i = 0; $i < count($rows); $i++) {
            $rows[$i]['sort_order'] = $i;

            if ($rows[$i]['item_type'] === TypeEnum::POTION || $rows[$i]['item_type'] === TypeEnum::JEWELRY) {
                continue;
            }

            if ($rows[$i]['repairable'] !== true) {
                continue;
            }

            if (! array_key_exists('max_durability', $rows[$i])) {
                $rows[$i]['max_durability'] = 40;
                $rows[$i]['durability_loss_per_fight'] = 1;
            }

            if (! array_key_exists('gem_slots', $rows[$i])) {
                $rows[$i]['gem_slots'] = 1;
            }
        }

        return $rows;
    }

    /**
     * @return array<string, int>
     */
    private function reqsForItem(string $itemId): array
    {
        return match ($itemId) {
            'knife_1' => ['req_level' => 1, 'req_agility' => 2, 'req_instinct' => 1],
            'axe_1' => ['req_level' => 1, 'req_strength' => 2, 'req_instinct' => 1],
            'club_1' => ['req_level' => 1, 'req_strength' => 2, 'req_vitality' => 1],
            'sword_0' => ['req_level' => 1, 'req_strength' => 1, 'req_agility' => 1],
            'hammer_0' => ['req_level' => 1, 'req_strength' => 2, 'req_instinct' => 1],
            'knife_4' => ['req_agility' => 2],
            'heavy_1' => ['req_vitality' => 1],
            'mobile_0', 'mobile_1', 'mobile_2', 'mobile_3' => ['req_vitality' => 1],
            'vital_0' => ['req_vitality' => 1],
            'knife_2' => ['req_level' => 2, 'req_agility' => 4, 'req_instinct' => 2],
            'axe_2' => ['req_level' => 2, 'req_strength' => 4, 'req_instinct' => 2, 'req_vitality' => 1],
            'club_2' => ['req_level' => 2, 'req_strength' => 4, 'req_vitality' => 2],
            'knife_3' => ['req_level' => 3, 'req_strength' => 2, 'req_agility' => 6, 'req_instinct' => 4, 'req_vitality' => 2],
            'axe_3' => ['req_level' => 3, 'req_strength' => 6, 'req_instinct' => 4, 'req_vitality' => 3],
            'club_3' => ['req_level' => 3, 'req_strength' => 6, 'req_instinct' => 2, 'req_vitality' => 4],
            'hammer_1' => ['req_level' => 3, 'req_strength' => 6, 'req_instinct' => 4, 'req_vitality' => 3],
            default => [],
        };
    }

    private function syncAppearanceImage(Equipment $equipment): void
    {
        $path = database_path('seeders/fixtures/equipment/' . $equipment->item_id . '.png');

        if (! is_file($path)) {
            return;
        }

        $equipment->clearMediaCollection('image');
        $equipment
            ->addMedia($path)
            ->preservingOriginal()
            ->toMediaCollection('image', 'local');
    }
}
