<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\Equipment\CurrencyEnum;
use App\Enums\Equipment\EffectTypeEnum;
use App\Enums\Equipment\EquipmentProfileEnum;
use App\Enums\Equipment\RepairTierEnum;
use App\Enums\Equipment\SlotEnum;
use App\Enums\Equipment\TypeEnum;
use App\Models\Equipment;
use Illuminate\Database\Seeder;

final class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->catalog() as $row) {
            Equipment::query()->updateOrCreate(
                ['item_id' => $row['item_id']],
                $row,
            );
        }
    }

    /**
     * Initial catalog snapshot for fresh installs / tests. Runtime SoT = `equipment` table.
     *
     * @return list<array<string, mixed>>
     */
    private function catalog(): array
    {
        return [
            [
                'item_id' => 'train_knife',
                'name' => 'Учебный нож',
                'description' => 'Лёгкий учебный клинок. Чуть повышает уворот и шанс крита.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::LIGHT,
                'tier' => 0,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 2,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 6,
                'mf_anti_dodge' => 0,
                'mf_crit' => 2,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 1,
                'repairable' => true,
            ],
            [
                'item_id' => 'train_axe',
                'name' => 'Учебный топор',
                'description' => 'Тяжёлый учебный топор. Бьёт сильнее и чаще критикует.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CLEAVE,
                'tier' => 0,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 3,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 2,
                'mf_crit' => 6,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 2,
                'repairable' => true,
            ],
            [
                'item_id' => 'train_club',
                'name' => 'Учебная дубина',
                'description' => 'Простая дубина тренера. Держит антиуворот и антикрит.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CRUSH,
                'tier' => 0,
                'in_shop' => true,
                'enabled' => true,
                'price' => 20,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 3,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 4,
                'mf_crit' => 0,
                'mf_anti_crit' => 4,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 3,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_t1',
                'name' => 'Короткий кинжал',
                'description' => 'Короткий кинжал новичка. Ставка на уворот и точные удары.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::LIGHT,
                'tier' => 1,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 4,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 10,
                'mf_anti_dodge' => 2,
                'mf_crit' => 4,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 4,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_t1',
                'name' => 'Лёгкий топор',
                'description' => 'Лёгкий боевой топор. Хороший крит за умеренную цену.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CLEAVE,
                'tier' => 1,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 5,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 4,
                'mf_crit' => 10,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 5,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_t1',
                'name' => 'Дубина новобранца',
                'description' => 'Дубина для строя. Усиливает контроль уворота и крита врага.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CRUSH,
                'tier' => 1,
                'in_shop' => true,
                'enabled' => true,
                'price' => 40,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 5,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 6,
                'mf_crit' => 2,
                'mf_anti_crit' => 6,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 6,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_t2',
                'name' => 'Боевой нож',
                'description' => 'Боевой нож наёмника. Заметно быстрее и острее учебного.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::LIGHT,
                'tier' => 2,
                'in_shop' => true,
                'enabled' => true,
                'price' => 100,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 7,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 16,
                'mf_anti_dodge' => 4,
                'mf_crit' => 6,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 7,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_t2',
                'name' => 'Боевой топор',
                'description' => 'Боевой топор рейдера. Высокий крит и давление в ближнем бою.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CLEAVE,
                'tier' => 2,
                'in_shop' => true,
                'enabled' => true,
                'price' => 100,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 8,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 8,
                'mf_crit' => 16,
                'mf_anti_crit' => 2,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 8,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_t2',
                'name' => 'Окованная дубина',
                'description' => 'Окованная дубина стража. Крепкий антикрит и антиуворот.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CRUSH,
                'tier' => 2,
                'in_shop' => true,
                'enabled' => true,
                'price' => 100,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 8,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 2,
                'mf_anti_dodge' => 10,
                'mf_crit' => 4,
                'mf_anti_crit' => 12,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 9,
                'repairable' => true,
            ],
            [
                'item_id' => 'knife_t3',
                'name' => 'Кинжал ассасина',
                'description' => 'Кинжал ассасина. Максимальный уворот в линейке ножей.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::LIGHT,
                'tier' => 3,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 11,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 24,
                'mf_anti_dodge' => 8,
                'mf_crit' => 10,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 10,
                'repairable' => true,
            ],
            [
                'item_id' => 'axe_t3',
                'name' => 'Топор берсерка',
                'description' => 'Топор берсерка. Пиковый крит и тяжёлый удар.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CLEAVE,
                'tier' => 3,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 12,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 14,
                'mf_crit' => 24,
                'mf_anti_crit' => 4,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 11,
                'repairable' => true,
            ],
            [
                'item_id' => 'club_t3',
                'name' => 'Молот стража',
                'description' => 'Молот стража. Лучшая защита от критов и уворотов врага.',
                'item_type' => TypeEnum::WEAPON,
                'slot' => SlotEnum::RIGHT_HAND,
                'profile' => EquipmentProfileEnum::CRUSH,
                'tier' => 3,
                'in_shop' => true,
                'enabled' => true,
                'price' => 250,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 12,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 4,
                'mf_anti_dodge' => 16,
                'mf_crit' => 6,
                'mf_anti_crit' => 20,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 12,
                'repairable' => true,
            ],
            [
                'item_id' => 'mail_shirt',
                'name' => 'Кольчуга',
                'description' => 'Кольчуга новобранца. Даёт запас прочности (бонус к max HP).',
                'item_type' => TypeEnum::ARMOR,
                'slot' => SlotEnum::ARMOR,
                'profile' => EquipmentProfileEnum::HEAVY,
                'tier' => 0,
                'in_shop' => false,
                'enabled' => true,
                'price' => 0,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 0,
                'stat_bonus' => 15,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_type' => null,
                'effect_value' => null,
                'sort_order' => 13,
                'repairable' => true,
            ],
            [
                'item_id' => 'health_potion',
                'name' => 'Зелье лечения',
                'description' => 'Флакон красного зелья. Восстанавливает HP в бою.',
                'item_type' => TypeEnum::POTION,
                'slot' => SlotEnum::POCKET,
                'profile' => EquipmentProfileEnum::HEAL,
                'tier' => null,
                'in_shop' => true,
                'enabled' => true,
                'price' => 15,
                'currency' => CurrencyEnum::SILVER,
                'vip_only' => false,
                'repair_tier' => RepairTierEnum::NORMAL,
                'weapon_damage' => 0,
                'stat_bonus' => 0,
                'armor' => 0,
                'mf_dodge' => 0,
                'mf_anti_dodge' => 0,
                'mf_crit' => 0,
                'mf_anti_crit' => 0,
                'effect_type' => EffectTypeEnum::HEAL_HP,
                'effect_value' => 40,
                'sort_order' => 14,
                'repairable' => false,
            ],
        ];
    }
}
